// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyowxsfzfuunjlufxqik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5b3d4c2Z6ZnV1bmpsdWZ4cWlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5OTY2MTYsImV4cCI6MjA3MDU3MjYxNn0.uRaFrjITY4tZLVkU9Et3WrpxXMkR03Pqjq_Mg9zOW3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});